<<<<<<< HEAD
import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";import{getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";import{getFirestore,collection,doc,query,orderBy,onSnapshot,writeBatch,addDoc,setDoc,updateDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
const config={apiKey:"AIzaSyCUnPUXtEwjY9_7tHPzv3DBTXok_Q_-398",authDomain:"progress-bar-ct.firebaseapp.com",projectId:"progress-bar-ct",storageBucket:"progress-bar-ct.firebasestorage.app",messagingSenderId:"113045520693",appId:"1:113045520693:web:612c1c08e9dc0d28c04c7c",measurementId:"G-SMS2YV6M31"};
const app=initializeApp(config),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);let students=[],selected="",results={},stopResults,repairDone=false;
const starters=[['marta','Марта'],['danila','Данила'],['viktoria','Виктория'],['elena','Елена'],['alexandra','Александра']];
const aliases={marta:'marta','марта':'marta',danila:'danila','данила':'danila',viktoria:'viktoria',victoria:'viktoria','виктория':'viktoria',elena:'elena','елена':'elena',alexandra:'alexandra','александра':'alexandra'};function personKey(name=''){const n=name.trim().toLowerCase();return aliases[n]||n}
function show(id,on=true){$(id).classList.toggle('hidden',!on)}function toast(t){$('toast').textContent='✓ '+t;show('toast');setTimeout(()=>show('toast',false),2000)}
onAuthStateChanged(auth,user=>{show('loading',false);show('login',!user);show('app',!!user);if(user)listenStudents()});
$('loginForm').onsubmit=async e=>{e.preventDefault();show('loginError',false);try{await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value);$('password').value=''}catch{show('loginError');$('loginError').textContent='Неверный email или пароль'}};$('logoutBtn').onclick=()=>signOut(auth);
function listenStudents(){onSnapshot(query(collection(db,'students'),orderBy('order')),async s=>{students=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.active!==false);const martas=students.filter(x=>personKey(x.name)==='marta');if(!repairDone&&martas.length>1&&martas.some(x=>x.id==='marta')){repairDone=true;await updateDoc(doc(db,'students','marta'),{active:false});toast('Лишняя копия Марты скрыта');return}$('studentCount').textContent=students.length;const missing=starters.filter(([,name])=>!students.some(s=>personKey(s.name)===personKey(name)));show('seedBtn',missing.length>0);$('seedBtn').textContent=students.length?`Добавить недостающих (${missing.length})`:'Добавить 5 учеников';if(!selected&&students[0])select(students[0].id);renderNav();if(!students.length){selected='';results={};render()}},()=>alert('Нет доступа к Firestore. Проверьте Rules.'))}
function renderNav(){$('studentList').innerHTML=students.map((s,i)=>`<button data-id="${s.id}" class="${selected===s.id?'active':''}"><i>${s.name[0]}</i><span>${s.name}<small>Открыть прогресс</small></span><em>${i+1}</em></button>`).join('');document.querySelectorAll('#studentList button').forEach(b=>b.onclick=()=>select(b.dataset.id))}
function select(id){selected=id;renderNav();if(stopResults)stopResults();stopResults=onSnapshot(collection(db,'students',id,'results'),s=>{results={};s.forEach(d=>results[d.id]=d.data());render()})}
function render(){const student=students.find(s=>s.id===selected);$('studentName').textContent=student?.name||'Выберите ученика';show('archiveBtn',!!student);if(!student){$('dashboard').innerHTML=`<div class="welcome"><h2>Добавьте учеников</h2><p>Подготовленный список можно создать одной кнопкой.</p><button class="primary" id="welcomeSeed">Добавить Марту и остальных</button></div>`;$('welcomeSeed')?.addEventListener('click',seed);return}const passed=[...Array(8)].filter((_,i)=>results[`credit_${String(i+1).padStart(2,'0')}`]?.passed).length,scores=[...Array(10)].map((_,i)=>results[`test_${String(i+1).padStart(2,'0')}`]?.score).filter(Number.isFinite),avg=scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):0;
$('dashboard').innerHTML=`<div class="stats"><article class="dark"><span>ОБЩИЙ ПРОГРЕСС</span><b>${Math.round(passed/8*100)}%</b><div class="bar"><i style="width:${passed/8*100}%"></i></div><p>${passed} из 8 зачётов сдано</p></article><article><span>ЗАЧЁТЫ</span><b>${passed}<small>/ 8</small></b><p class="green">Цель — не менее 75%</p></article><article><span>СРЕДНИЙ БАЛЛ</span><b>${avg}<small>/ 100</small></b><p>${scores.length} из 10 тестов</p></article></div>${section('01','Зачёты','Следующий этап открывается после результата 75% и выше',`${passed} / 8`,credits())}${section('02','Тренировочные тесты','Максимальный результат каждого теста — 100 баллов',`${scores.length} / 10`,tests())}`;bindScores()}
function section(n,t,p,b,c){return`<section class="section"><div class="section-head"><div><i>${n}</i><div><h2>${t}</h2><p>${p}</p></div></div><b>${b}</b></div>${c}</section>`}
function credits(){return`<div class="credits">${[...Array(8)].map((_,i)=>{const id=`credit_${String(i+1).padStart(2,'0')}`,r=results[id],locked=i>0&&!results[`credit_${String(i).padStart(2,'0')}`]?.passed;return`<article class="${r?.passed?'passed':''} ${locked?'locked':''}"><div class="card-top"><span>${String(i+1).padStart(2,'0')}</span><i>${locked?'⌁':r?.passed?'✓':'○'}</i></div><h3>Зачёт ${i+1}</h3>${locked?`<p>Сначала сдайте зачёт ${i}</p>`:`<label>Результат<div><input data-id="${id}" data-type="credit" type="number" min="0" max="100" value="${r?.score??''}" placeholder="—"><b>%</b></div></label><p>${r?(r.passed?'Сдано':'Нужна ещё попытка'):'Минимум 75%'}</p>`}</article>`}).join('')}</div>`}
function tests(){return`<div class="tests">${[...Array(10)].map((_,i)=>{const id=`test_${String(i+1).padStart(2,'0')}`;return`<label><span>Тест ${String(i+1).padStart(2,'0')}</span><div><input data-id="${id}" data-type="test" type="number" min="0" max="100" value="${results[id]?.score??''}" placeholder="—"><small>/100</small></div></label>`}).join('')}</div>`}
function bindScores(){document.querySelectorAll('[data-type]').forEach(x=>x.onchange=()=>save(x.dataset.id,x.value,x.dataset.type))}async function save(id,v,type){if(v==='')return;const score=Math.max(0,Math.min(100,Number(v)||0));await setDoc(doc(db,'students',selected,'results',id),{assessmentId:id,score,maxScore:100,percent:score,...(type==='credit'?{passed:score>=75}:{}),attempts:(results[id]?.attempts||0)+1,updatedAt:serverTimestamp()},{merge:true});toast('Результат сохранён')}
async function seed(){const missing=starters.filter(([,name])=>!students.some(s=>personKey(s.name)===personKey(name)));if(!missing.length)return;const b=writeBatch(db);missing.forEach(([id,name])=>b.set(doc(db,'students',id),{name,order:starters.findIndex(x=>x[1]===name)+1,active:true},{merge:true}));await b.commit();toast(`Добавлено учеников: ${missing.length}`)}$('seedBtn').onclick=seed;$('addBtn').onclick=()=>{show('modal');$('newName').focus()};$('closeModal').onclick=()=>show('modal',false);$('modal').onclick=e=>{if(e.target===$('modal'))show('modal',false)};$('addForm').onsubmit=async e=>{e.preventDefault();const r=await addDoc(collection(db,'students'),{name:$('newName').value.trim(),order:Date.now(),active:true});$('newName').value='';show('modal',false);select(r.id);toast('Ученик добавлен')};$('archiveBtn').onclick=async()=>{const s=students.find(x=>x.id===selected);if(s&&confirm(`Скрыть «${s.name}»? Результаты сохранятся.`)){await updateDoc(doc(db,'students',s.id),{active:false});selected=''}};
=======
import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";import{getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";import{getFirestore,collection,doc,query,orderBy,onSnapshot,writeBatch,addDoc,setDoc,updateDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
const config={apiKey:"AIzaSyCUnPUXtEwjY9_7tHPzv3DBTXok_Q_-398",authDomain:"progress-bar-ct.firebaseapp.com",projectId:"progress-bar-ct",storageBucket:"progress-bar-ct.firebasestorage.app",messagingSenderId:"113045520693",appId:"1:113045520693:web:612c1c08e9dc0d28c04c7c",measurementId:"G-SMS2YV6M31"};
const app=initializeApp(config),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);let students=[],selected="",results={},stopResults,repairDone=false,currentUser=null,studentsStarted=false;
const starters=[['marta','Марта'],['danila','Данила'],['viktoria','Виктория'],['elena','Елена'],['alexandra','Александра']];
const aliases={marta:'marta','марта':'marta',danila:'danila','данила':'danila',viktoria:'viktoria',victoria:'viktoria','виктория':'viktoria',elena:'elena','елена':'elena',alexandra:'alexandra','александра':'alexandra'};function personKey(name=''){const n=name.trim().toLowerCase();return aliases[n]||n}
function show(id,on=true){$(id).classList.toggle('hidden',!on)}function toast(t){$('toast').textContent='✓ '+t;show('toast');setTimeout(()=>show('toast',false),2000)}
onAuthStateChanged(auth,user=>{currentUser=user;show('loading',false);show('app');show('login',false);show('teacherLoginBtn',!user);show('logoutBtn',!!user);show('addBtn',!!user);$('modeBadge').textContent=user?'● Режим редактирования':'◉ Только просмотр';document.body.classList.toggle('is-editor',!!user);if(!studentsStarted){studentsStarted=true;listenStudents()}else render()});
$('teacherLoginBtn').onclick=()=>show('login');$('closeLogin').onclick=()=>show('login',false);$('login').onclick=e=>{if(e.target===$('login'))show('login',false)};$('loginForm').onsubmit=async e=>{e.preventDefault();show('loginError',false);try{await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value);$('password').value=''}catch{show('loginError');$('loginError').textContent='Неверный email или пароль'}};$('logoutBtn').onclick=()=>signOut(auth);
function listenStudents(){onSnapshot(query(collection(db,'students'),orderBy('order')),async s=>{students=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.active!==false);const martas=students.filter(x=>personKey(x.name)==='marta');if(currentUser&&!repairDone&&martas.length>1&&martas.some(x=>x.id==='marta')){repairDone=true;await updateDoc(doc(db,'students','marta'),{active:false});toast('Лишняя копия Марты скрыта');return}$('studentCount').textContent=students.length;const missing=starters.filter(([,name])=>!students.some(s=>personKey(s.name)===personKey(name)));show('seedBtn',!!currentUser&&missing.length>0);$('seedBtn').textContent=students.length?`Добавить недостающих (${missing.length})`:'Добавить 5 учеников';if(!selected&&students[0])select(students[0].id);renderNav();if(!students.length){selected='';results={};render()}},()=>alert('Нет доступа к Firestore. Опубликуйте обновлённые Rules.'))}
function avatar(name){const key=personKey(name);return `assets/avatar-${key}.png`}function renderNav(){$('studentList').innerHTML=students.map((s,i)=>`<button data-id="${s.id}" class="${selected===s.id?'active':''}"><i><img src="${avatar(s.name)}" alt="Аватар ${s.name}" onerror="this.style.display='none';this.parentElement.textContent='${s.name[0]}'"></i><span>${s.name}<small>Открыть прогресс</small></span><em>${i+1}</em></button>`).join('');document.querySelectorAll('#studentList button').forEach(b=>b.onclick=()=>select(b.dataset.id))}
function select(id){selected=id;renderNav();if(stopResults)stopResults();stopResults=onSnapshot(collection(db,'students',id,'results'),s=>{results={};s.forEach(d=>results[d.id]=d.data());render()})}
function render(){const student=students.find(s=>s.id===selected);$('studentName').textContent=student?.name||'Выберите ученика';show('archiveBtn',!!student&&!!currentUser);if(!student){$('dashboard').innerHTML=`<div class="welcome"><h2>${currentUser?'Добавьте учеников':'Пока нет учеников'}</h2><p>${currentUser?'Подготовленный список можно создать одной кнопкой.':'Прогресс появится после добавления учеников преподавателем.'}</p>${currentUser?'<button class="primary" id="welcomeSeed">Добавить Марту и остальных</button>':''}</div>`;$('welcomeSeed')?.addEventListener('click',seed);return}const passed=[...Array(8)].filter((_,i)=>results[`credit_${String(i+1).padStart(2,'0')}`]?.passed).length,scores=[...Array(10)].map((_,i)=>results[`test_${String(i+1).padStart(2,'0')}`]?.score).filter(Number.isFinite),avg=scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):0;
$('dashboard').innerHTML=`<div class="stats"><article class="dark"><span>ОБЩИЙ ПРОГРЕСС</span><b>${Math.round(passed/8*100)}%</b><div class="bar"><i style="width:${passed/8*100}%"></i></div><p>${passed} из 8 зачётов сдано</p></article><article><span>ЗАЧЁТЫ</span><b>${passed}<small>/ 8</small></b><p class="green">Цель — не менее 75%</p></article><article><span>СРЕДНИЙ БАЛЛ</span><b>${avg}<small>/ 100</small></b><p>${scores.length} из 10 тестов</p></article></div>${section('01','Зачёты','Следующий этап открывается после результата 75% и выше',`${passed} / 8`,credits())}${section('02','Тренировочные тесты','Максимальный результат каждого теста — 100 баллов',`${scores.length} / 10`,tests())}`;bindScores()}
function section(n,t,p,b,c){return`<section class="section"><div class="section-head"><div><i>${n}</i><div><h2>${t}</h2><p>${p}</p></div></div><b>${b}</b></div>${c}</section>`}
function credits(){return`<div class="credits">${[...Array(8)].map((_,i)=>{const id=`credit_${String(i+1).padStart(2,'0')}`,r=results[id],locked=i>0&&!results[`credit_${String(i).padStart(2,'0')}`]?.passed;return`<article class="${r?.passed?'passed':''} ${locked?'locked':''}"><div class="card-top"><span>${String(i+1).padStart(2,'0')}</span><i>${locked?'⌁':r?.passed?'✓':'○'}</i></div><h3>Зачёт ${i+1}</h3>${locked?`<p>Сначала сдайте зачёт ${i}</p>`:`<label>Результат<div><input data-id="${id}" data-type="credit" type="number" min="0" max="100" value="${r?.score??''}" placeholder="—"><b>%</b></div></label><p>${r?(r.passed?'Сдано':'Нужна ещё попытка'):'Минимум 75%'}</p>`}</article>`}).join('')}</div>`}
function tests(){return`<div class="tests">${[...Array(10)].map((_,i)=>{const id=`test_${String(i+1).padStart(2,'0')}`;return`<label><span>Тест ${String(i+1).padStart(2,'0')}</span><div><input data-id="${id}" data-type="test" type="number" min="0" max="100" value="${results[id]?.score??''}" placeholder="—"><small>/100</small></div></label>`}).join('')}</div>`}
function bindScores(){document.querySelectorAll('[data-type]').forEach(x=>{x.disabled=!currentUser;x.title=currentUser?'Введите результат':'Только преподаватель может менять результат';if(currentUser)x.onchange=()=>save(x.dataset.id,x.value,x.dataset.type)})}async function save(id,v,type){if(!currentUser||v==='')return;const score=Math.max(0,Math.min(100,Number(v)||0));await setDoc(doc(db,'students',selected,'results',id),{assessmentId:id,score,maxScore:100,percent:score,...(type==='credit'?{passed:score>=75}:{}),attempts:(results[id]?.attempts||0)+1,updatedAt:serverTimestamp()},{merge:true});toast('Результат сохранён')}
async function seed(){const missing=starters.filter(([,name])=>!students.some(s=>personKey(s.name)===personKey(name)));if(!missing.length)return;const b=writeBatch(db);missing.forEach(([id,name])=>b.set(doc(db,'students',id),{name,order:starters.findIndex(x=>x[1]===name)+1,active:true},{merge:true}));await b.commit();toast(`Добавлено учеников: ${missing.length}`)}$('seedBtn').onclick=seed;$('addBtn').onclick=()=>{show('modal');$('newName').focus()};$('closeModal').onclick=()=>show('modal',false);$('modal').onclick=e=>{if(e.target===$('modal'))show('modal',false)};$('addForm').onsubmit=async e=>{e.preventDefault();const r=await addDoc(collection(db,'students'),{name:$('newName').value.trim(),order:Date.now(),active:true});$('newName').value='';show('modal',false);select(r.id);toast('Ученик добавлен')};$('archiveBtn').onclick=async()=>{const s=students.find(x=>x.id===selected);if(s&&confirm(`Скрыть «${s.name}»? Результаты сохранятся.`)){await updateDoc(doc(db,'students',s.id),{active:false});selected=''}};
>>>>>>> d164b0d (Add public view and student avatars)
